### PR TITLE
DB and scraper section update

### PR DESCRIPTION
**Pull request by zhilongz**
1. database.py:
   (a) added fields reviewID, review rating and total number of review to db
   (b) added has_review_id() to check if review already stored in db
   (c) added update_contents_for_product_id to append new review data to
   existing data instead of overwrite existing data
   2update_contents_for_product_id. scraper.py:
   (a) backup scraper that scrape from html if amazon API failed
   (b) currently scrape contents, reviewID, review rating, and total number of reviews
   (c) checking if a review in db before scrape content
2. srs_local.py:
   (a) logic: (i) check if product has any review

NO -> trigger scraper, process review, store data
Otherwise -> check if content is processed
If yes -> scrape only new review no in db, process review, update db
TO DO:
1. edit load_db_from_files() in database.py to handle stanford data instead of txt data
2. processing review after scraping is slow, may consider speeding it up

### CODE REVIEW

**Comment by zhilongz** [comment]
conflict resolved and tested

**Comment by KEHANG** [comment]
do we still need the previous pull request #44 ?

**Comment by zhilongz** [comment]
no

**Comment by KEHANG** [comment]
already merged in #48

**Pull request closed without merging**
